package com.hoangnv97.moviedemo.infra

enum class ApiEnum {
    API_VIDEO_LIST,
    API_COMING_SOON,
    API_TV_SHOW_VIDEO_LIST,
    API_TV_SHOW_DETAIL,
    API_DISCOVER_TV_SHOW_LIST,
    API_TV_SHOW_CAST_LIST,
    API_POPULAR,
    API_IMAGE_CAST_LIST,
    API_CAST_INFO,
    API_RELATED_MOVIE,
    API_DISCOVER_MOVIES,
    API_MOVIE_DETAIL,
    API_MOVIE_LIST,
    API_GENRE_LIST,
    API_CAST_LIST,
    API_LOGIN,
    API_LOCAL,
    API_REGISTER,
    UNCLASSIFIED
}
